export class STORAGE_GLOBALS {
  public static USER_TOKEN = "USER_TOKEN";
  public static USER_REFERENCE_ID = "USER_REFERENCE_ID";
  public static USER_REGISTERED_DATE = "USER_REGISTERED_DATE";
  public static USER_REGISTERED_EMAIL = "USER_REGISTERED_EMAIL";
}
