/**
 * Pango API
 * Move you App forwad with Pango API
 *
 * OpenAPI spec version: 0.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface PropertyDetailResource {
    propertyReferenceId?: string;

    /**
     * Unit number of the property
     */
    propertyUnitId?: string;

    /**
     * summary description of the property
     */
    propertyDescription?: string;

    /**
     * Information representing whether the property is for rent or sale
     */
    listingFor?: string;

    propertyRent?: models.PropertyRent;

    propertyFeature?: models.PropertyFeature;

    /**
     * Value represeanting whether the property is available now or soon
     */
    availability?: string;

    /**
     * Available on (future date) or available since (past date)
     */
    availableOn?: string;

    /**
     * Indicates whether the property should be auto-listed once the current rental expires
     */
    autoListInd?: boolean;

    /**
     * Number representing everage stars rating out of 5 for this property
     */
    rating?: number;

    /**
     * Total number of tenant reviews on this property to date
     */
    reviewCount?: number;

    coverPhoto?: models.Attachment;

    /**
     * Images encoded in base64 representing the property
     */
    photoUrl?: Array<models.Attachment>;

    /**
     * Longitide[0] and Latitude[1] location components of this property. For Example [-73.93383000695911, 40.81949109558767] implying a property is located at -73.93414657 longitude and 40.82302903 latitude.
     */
    location?: Array<number>;

    /**
     * Physical address of the
     */
    address?: string;

    /**
     * value representing the reference Id of the owner
     */
    ownerReferenceId?: string;

    /**
     * Terms,  conditions and any restrictions information
     */
    terms?: string;

    /**
     * Indicates whether the property is active or not
     */
    active?: boolean;

}
